// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=service_mock_test.go -package=queue
//

// Package queue is a generated GoMock package.
package queue

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/art-es/queue-service/internal/app/domain"
	gomock "go.uber.org/mock/gomock"
)

// Mockclock is a mock of clock interface.
type Mockclock struct {
	ctrl     *gomock.Controller
	recorder *MockclockMockRecorder
	isgomock struct{}
}

// MockclockMockRecorder is the mock recorder for Mockclock.
type MockclockMockRecorder struct {
	mock *Mockclock
}

// NewMockclock creates a new mock instance.
func NewMockclock(ctrl *gomock.Controller) *Mockclock {
	mock := &Mockclock{ctrl: ctrl}
	mock.recorder = &MockclockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockclock) EXPECT() *MockclockMockRecorder {
	return m.recorder
}

// Now mocks base method.
func (m *Mockclock) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now.
func (mr *MockclockMockRecorder) Now() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*Mockclock)(nil).Now))
}

// MockidempotencyKeyCache is a mock of idempotencyKeyCache interface.
type MockidempotencyKeyCache struct {
	ctrl     *gomock.Controller
	recorder *MockidempotencyKeyCacheMockRecorder
	isgomock struct{}
}

// MockidempotencyKeyCacheMockRecorder is the mock recorder for MockidempotencyKeyCache.
type MockidempotencyKeyCacheMockRecorder struct {
	mock *MockidempotencyKeyCache
}

// NewMockidempotencyKeyCache creates a new mock instance.
func NewMockidempotencyKeyCache(ctrl *gomock.Controller) *MockidempotencyKeyCache {
	mock := &MockidempotencyKeyCache{ctrl: ctrl}
	mock.recorder = &MockidempotencyKeyCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockidempotencyKeyCache) EXPECT() *MockidempotencyKeyCacheMockRecorder {
	return m.recorder
}

// GetQueuePush mocks base method.
func (m *MockidempotencyKeyCache) GetQueuePush(key string) (*domain.Task, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQueuePush", key)
	ret0, _ := ret[0].(*domain.Task)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetQueuePush indicates an expected call of GetQueuePush.
func (mr *MockidempotencyKeyCacheMockRecorder) GetQueuePush(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQueuePush", reflect.TypeOf((*MockidempotencyKeyCache)(nil).GetQueuePush), key)
}

// SetQueuePush mocks base method.
func (m *MockidempotencyKeyCache) SetQueuePush(key string, result *domain.Task) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetQueuePush", key, result)
}

// SetQueuePush indicates an expected call of SetQueuePush.
func (mr *MockidempotencyKeyCacheMockRecorder) SetQueuePush(key, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetQueuePush", reflect.TypeOf((*MockidempotencyKeyCache)(nil).SetQueuePush), key, result)
}

// MocktaskRepository is a mock of taskRepository interface.
type MocktaskRepository struct {
	ctrl     *gomock.Controller
	recorder *MocktaskRepositoryMockRecorder
	isgomock struct{}
}

// MocktaskRepositoryMockRecorder is the mock recorder for MocktaskRepository.
type MocktaskRepositoryMockRecorder struct {
	mock *MocktaskRepository
}

// NewMocktaskRepository creates a new mock instance.
func NewMocktaskRepository(ctrl *gomock.Controller) *MocktaskRepository {
	mock := &MocktaskRepository{ctrl: ctrl}
	mock.recorder = &MocktaskRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktaskRepository) EXPECT() *MocktaskRepositoryMockRecorder {
	return m.recorder
}

// GetFirstPending mocks base method.
func (m *MocktaskRepository) GetFirstPending(ctx context.Context, queueName string) (*domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFirstPending", ctx, queueName)
	ret0, _ := ret[0].(*domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFirstPending indicates an expected call of GetFirstPending.
func (mr *MocktaskRepositoryMockRecorder) GetFirstPending(ctx, queueName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFirstPending", reflect.TypeOf((*MocktaskRepository)(nil).GetFirstPending), ctx, queueName)
}

// Save mocks base method.
func (m *MocktaskRepository) Save(ctx context.Context, task *domain.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MocktaskRepositoryMockRecorder) Save(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MocktaskRepository)(nil).Save), ctx, task)
}
