// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=service_mock_test.go -package=task
//

// Package task is a generated GoMock package.
package task

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/art-es/queue-service/internal/app/domain"
	gomock "go.uber.org/mock/gomock"
)

// Mockclock is a mock of clock interface.
type Mockclock struct {
	ctrl     *gomock.Controller
	recorder *MockclockMockRecorder
	isgomock struct{}
}

// MockclockMockRecorder is the mock recorder for Mockclock.
type MockclockMockRecorder struct {
	mock *Mockclock
}

// NewMockclock creates a new mock instance.
func NewMockclock(ctrl *gomock.Controller) *Mockclock {
	mock := &Mockclock{ctrl: ctrl}
	mock.recorder = &MockclockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockclock) EXPECT() *MockclockMockRecorder {
	return m.recorder
}

// Now mocks base method.
func (m *Mockclock) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now.
func (mr *MockclockMockRecorder) Now() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*Mockclock)(nil).Now))
}

// MockidempotencyKeyCache is a mock of idempotencyKeyCache interface.
type MockidempotencyKeyCache struct {
	ctrl     *gomock.Controller
	recorder *MockidempotencyKeyCacheMockRecorder
	isgomock struct{}
}

// MockidempotencyKeyCacheMockRecorder is the mock recorder for MockidempotencyKeyCache.
type MockidempotencyKeyCacheMockRecorder struct {
	mock *MockidempotencyKeyCache
}

// NewMockidempotencyKeyCache creates a new mock instance.
func NewMockidempotencyKeyCache(ctrl *gomock.Controller) *MockidempotencyKeyCache {
	mock := &MockidempotencyKeyCache{ctrl: ctrl}
	mock.recorder = &MockidempotencyKeyCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockidempotencyKeyCache) EXPECT() *MockidempotencyKeyCacheMockRecorder {
	return m.recorder
}

// HasTaskAck mocks base method.
func (m *MockidempotencyKeyCache) HasTaskAck(key string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasTaskAck", key)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasTaskAck indicates an expected call of HasTaskAck.
func (mr *MockidempotencyKeyCacheMockRecorder) HasTaskAck(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasTaskAck", reflect.TypeOf((*MockidempotencyKeyCache)(nil).HasTaskAck), key)
}

// HasTaskNack mocks base method.
func (m *MockidempotencyKeyCache) HasTaskNack(key string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasTaskNack", key)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasTaskNack indicates an expected call of HasTaskNack.
func (mr *MockidempotencyKeyCacheMockRecorder) HasTaskNack(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasTaskNack", reflect.TypeOf((*MockidempotencyKeyCache)(nil).HasTaskNack), key)
}

// SetTaskAck mocks base method.
func (m *MockidempotencyKeyCache) SetTaskAck(key string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTaskAck", key)
}

// SetTaskAck indicates an expected call of SetTaskAck.
func (mr *MockidempotencyKeyCacheMockRecorder) SetTaskAck(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTaskAck", reflect.TypeOf((*MockidempotencyKeyCache)(nil).SetTaskAck), key)
}

// SetTaskNack mocks base method.
func (m *MockidempotencyKeyCache) SetTaskNack(key string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTaskNack", key)
}

// SetTaskNack indicates an expected call of SetTaskNack.
func (mr *MockidempotencyKeyCacheMockRecorder) SetTaskNack(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTaskNack", reflect.TypeOf((*MockidempotencyKeyCache)(nil).SetTaskNack), key)
}

// MocktaskRepository is a mock of taskRepository interface.
type MocktaskRepository struct {
	ctrl     *gomock.Controller
	recorder *MocktaskRepositoryMockRecorder
	isgomock struct{}
}

// MocktaskRepositoryMockRecorder is the mock recorder for MocktaskRepository.
type MocktaskRepositoryMockRecorder struct {
	mock *MocktaskRepository
}

// NewMocktaskRepository creates a new mock instance.
func NewMocktaskRepository(ctrl *gomock.Controller) *MocktaskRepository {
	mock := &MocktaskRepository{ctrl: ctrl}
	mock.recorder = &MocktaskRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktaskRepository) EXPECT() *MocktaskRepositoryMockRecorder {
	return m.recorder
}

// Complete mocks base method.
func (m *MocktaskRepository) Complete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Complete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Complete indicates an expected call of Complete.
func (mr *MocktaskRepositoryMockRecorder) Complete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Complete", reflect.TypeOf((*MocktaskRepository)(nil).Complete), ctx, id)
}

// GetProcessingWithID mocks base method.
func (m *MocktaskRepository) GetProcessingWithID(ctx context.Context, id string) (*domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProcessingWithID", ctx, id)
	ret0, _ := ret[0].(*domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProcessingWithID indicates an expected call of GetProcessingWithID.
func (mr *MocktaskRepositoryMockRecorder) GetProcessingWithID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProcessingWithID", reflect.TypeOf((*MocktaskRepository)(nil).GetProcessingWithID), ctx, id)
}

// Save mocks base method.
func (m *MocktaskRepository) Save(ctx context.Context, task *domain.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MocktaskRepositoryMockRecorder) Save(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MocktaskRepository)(nil).Save), ctx, task)
}
